version: '3.9'
services:
  app:
    build:
      context: /home/jose/jmg/universidad/Practica-sre
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../../mvc:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: data_uptaeb
      MYSQL_USER: root_user
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
    restart: always
    ports:
      - "6033:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1